"""Public trace parser for LOG_LEVEL2 verifier state traces."""

from __future__ import annotations

from .trace_parser_impl import (
    BacktrackChain,
    BacktrackInfo,
    BacktrackLine,
    BacktrackLink,
    CausalChain,
    ChainLink,
    CriticalTransition,
    ErrorLine,
    InstructionLine,
    OtherLine,
    ParsedTrace,
    RegisterState,
    RegisterStateLine,
    SourceAnnotation,
    TraceLine,
    TracedInstruction,
    _is_pointer_type,
    extract_backtrack_chains,
    parse_line,
    parse_trace,
    parse_verifier_trace,
)

__all__ = [
    "BacktrackChain",
    "BacktrackInfo",
    "BacktrackLine",
    "BacktrackLink",
    "CausalChain",
    "ChainLink",
    "CriticalTransition",
    "ErrorLine",
    "InstructionLine",
    "OtherLine",
    "ParsedTrace",
    "RegisterState",
    "RegisterStateLine",
    "SourceAnnotation",
    "TraceLine",
    "TracedInstruction",
    "_is_pointer_type",
    "extract_backtrack_chains",
    "parse_line",
    "parse_trace",
    "parse_verifier_trace",
]
